# Generated by Django 5.1.6 on 2025-04-03 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='imageBase64',
            field=models.TextField(blank=True, null=True),
        ),
    ]
