# Generated by Django 5.1.6 on 2025-02-24 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='email',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='Gener',
            new_name='Gender',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='name',
            new_name='Name',
        ),
    ]
