# Generated by Django 5.1.6 on 2025-04-03 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_account_imagebase64'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='imageBase64',
            new_name='ImageBase64',
        ),
    ]
