# Generated by Django 5.1.6 on 2025-02-24 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_rename_email_account_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='Email',
            new_name='email',
        ),
    ]
