# Generated by Django 5.1.6 on 2025-04-03 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_rename_imagebase64_account_imagebase64'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='ImageBase64',
            new_name='Avatar',
        ),
    ]
