# Generated by Django 5.1.6 on 2025-02-24 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_rename_email_account_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='Name',
            field=models.CharField(max_length=50),
        ),
    ]
