# Generated by Django 5.1.6 on 2025-02-24 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_account_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_manufacturer',
            field=models.BooleanField(default=False),
        ),
    ]
