# Generated by Django 5.1.6 on 2025-03-02 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='potregistry',
            name='Key',
            field=models.CharField(default='XXXX-XXXX-XXXX', editable=False, max_length=14),
        ),
        migrations.AlterField(
            model_name='potregistry',
            name='Name',
            field=models.CharField(default='Smart Plant Pot', max_length=50),
        ),
    ]
