# Generated by Django 5.1.6 on 2025-02-25 08:23

import plant.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0002_alter_plan_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='potregistry',
            name='Key',
            field=models.CharField(default=plant.models.GeneratePotKey, max_length=14),
        ),
    ]
