# Generated by Django 5.1.6 on 2025-03-05 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0002_alter_potregistry_key_alter_potregistry_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='JSON',
            field=models.CharField(default='Some JSON', max_length=1000),
        ),
    ]
