# Generated by Django 5.1.6 on 2025-02-25 08:27

import plant.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0003_potregistry_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='potregistry',
            name='Key',
            field=models.CharField(default=plant.models.GeneratePotKey, editable=False, max_length=14),
        ),
    ]
